### ISSUE TITLE
UI glitches (internal viewer text selection, main menu) with Qt 5 version running on GNOME

### ISSUE THREAD

**Issue by skipperTux** [doublecmd/doublecmd#1345]
### Version

Double Commander
Version: 1.0.11
Revision: 272
Commit: 0b8ba3838
Build date: 2017/01/01
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Fedora release 38 (Thirty Eight)

Widgetset library: Qt 5.15.11, libQt5Pas 5.6.1

### Description

Issue #927 suggests using the Double Commander Qt5 version for native Wayland support, also in GNOME desktop. I made two screen-casts showing UI glitches I have with the Qt5 version running on Fedora 38 (GNOME). I also tested this with Fedora 39 (GNOME) in a VM, same issue.

I assume both are related to DC-qt running on GNOME. I do not have these issues with other Qt5 applications, like [KeePassXC](https://keepassxc.org/) or [QOwnNotes](https://www.qownnotes.org/).

The first cast shows selecting text with the mouse in the internal viewer. The text selection does not match the mouse cursor position. The more right the mouse cursor is, the greater the difference gets.
[Screencast from 2023-11-14 12-40-28.webm](https://github.com/doublecmd/doublecmd/assets/3322442/65af1c70-2de9-48b3-b38b-58c5cd0917e2)

The second cast shows the main menu, opening first time is OK, when moving the mouse cursor, the menu position is wrong. This also happens within the menu of the internal viewer.
[Screencast from 2023-11-14 12-41-45.webm](https://github.com/doublecmd/doublecmd/assets/3322442/5a5c150a-4215-4a03-ae17-23cde5fbeaa7)

**Comment by alexx2000** [comment]
1. https://doublecmd.github.io/doc/en/faq.html#f3_font or use DC 1.1.5 beta.
2. Lazarus/Qt bug.

**Comment by skipperTux** [comment]
Thanks for the fast response. Shall we close this issue or keep it open because of "2. Lazarus/Qt bug."?

**Comment by alexx2000** [comment]
Second bug should be reported to Lazarus. Maybe I will do it.

**Comment by skipperTux** [comment]
@pwn0r Setting `Configuration->Options->Tools->Fonts->Viewer Font` to something like `Fira Code` or `Inconsolata` fixed the text selection issue for me.

**Comment by alexx2000** [comment]
Double Commander 1.1.5 beta auto choose correct monospace font only at the first "clean" start (without previous configuration files).

**Comment by zeljan1** [comment]
Guys, I've fixed https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/40602 , please test asap since 3.0 release is just around the corner :)

**Comment by skipperTux** [comment]
With regards to issue 2. (menu position): I still have that issue in Fedora 39 with DC 1.1.11 beta. The reason is because that version is still build with Lazarus 2.2.6.0, see below [*]. Lazarus 3.2 has been released end of February. Is this a Fedora packaging issue, as in the [release notes for 1.1.0](https://github.com/doublecmd/doublecmd/wiki/Changes-in-version-1.1.0) I find _Qt 6 widgetset support (Lazarus 3.0)_?

[*] Double Commander
Version: 1.1.11 beta
Revision: 410
Commit: f1b449635
Build date: 2024/03/15
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Fedora release 39 (Thirty Nine)

Widgetset library: Qt 5.15.12, libQt5Pas 5.6.1

**Comment by skipperTux** [comment]
Same with the latest AppImage snapshot on my machine. As I understand [the post](https://github.com/doublecmd/doublecmd/issues/1345#issuecomment-1817212666) from @zeljan1 the fix made it into Lazarus version 3.0+.

**Comment by alexx2000** [comment]
You can try portable [Qt6 version](https://sourceforge.net/projects/doublecmd/files/DC%20for%20Linux%2064%20bit/Double%20Commander%201.1.11%20beta/doublecmd-1.1.11.qt6.x86_64.tar.xz/download) (built using Lazarus 3.2).

**Comment by skipperTux** [comment]
The portable Qt6 version does not have the issue. Thanks.
Any time-frame when this version will be available as package (rpm) via Build Service?

**Comment by alexx2000** [comment]
After Fedora 40 release.

**Comment by rwperrott** [comment]
On Mint 22.1 64-bit XFCE
Glitches for the 24.04 Ubuntu 64-bit one via Mint 22.1, with the latest AppImage 64-bit one.
Can't install 24.04 Ubuntu Qt6 deb, to try, because of too new QT6 lib.
