### ISSUE TITLE
Weird looking font in viewer and editor by default in linux

### ISSUE THREAD

**Issue by maxpozdeev** [doublecmd/doublecmd#2062]
### Version

Version: 1.2.0 alpha
Revision: 11772
Commit: cad083f
Build date: 2025/01/07
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: KDE neon User Edition
Widgetset library: Qt 5.15.16

Operating System: KDE neon 6.2
KDE Plasma Version: 6.2.5
KDE Frameworks Version: 6.9.0
Qt Version: 6.8.1
Kernel Version: 6.8.0-51-generic (64-bit)
Graphics Platform: X11

### Description

After installing and not changing any settings If we open a file in viewer we get weird looking font (huge spacing):
![viewer](https://github.com/user-attachments/assets/3dc414cd-0944-4506-b61f-322fceb255cf)

Font settings in KDE Neon:
![font settings](https://github.com/user-attachments/assets/c4755451-f2ef-42de-be43-b045a93d15d9)

```
$ fc-match monospace
Hack-Regular.ttf: "Hack" "Regular"

$ fc-list | grep Hack
/usr/share/fonts/truetype/hack/Hack-Regular.ttf: Hack:style=Regular
/usr/share/fonts/truetype/hack/Hack-Bold.ttf: Hack:style=Bold
/usr/share/fonts/truetype/hack/Hack-BoldItalic.ttf: Hack:style=Bold Italic
/usr/share/fonts/truetype/hack/Hack-Italic.ttf: Hack:style=Italic
```

If we select the same font via app settings we see trailing 'Regular' is removed and font in viewer looks as suggested.
![after](https://github.com/user-attachments/assets/4e63aab4-4d98-43a4-a37e-731fcb9f922e)
![viewer-after](https://github.com/user-attachments/assets/6a33d1ec-6843-42d5-b26f-0715e6f13898)

Probably something broken in font detection code in [GetFontName()](https://github.com/doublecmd/doublecmd/blob/cad083f6e8a0fa7e60baefe589336e4e6fdd5be7/src/platform/unix/umyunix.pas#L608).

**Comment by alexx2000** [comment]
Maybe fixed.

**Comment by maxpozdeev** [comment]
Thank you! 
Just checked latest doublecmd-qt-0-Build1720.1.glibc2.10-x86_64.AppImage in KDE Neon User and ALT Linux K 11 - fonts  on fresh install are ok!

**Comment by dandv** [comment]
I think the problem has been fixed, thank you!

For those who land here, pre-release builds are https://doublecmd.sourceforge.io/site/eng/snapshots.php

With the QT AppImage form the URL, I see this when launching:

```
$ rm -rf /home/dandv/.config/doublecmd
$ ./doublecmd-qt-latest-x86_64_2023-02-11.AppImage 
SystemLocale en_US
SystemLanguage en
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
Monospace: Noto Sans Mono
ImageMagick: libMagickWand-7.Q16HDRI.so.10
Starting GuiMessageQueue
Starting Double Commander
Double Commander 1.2.0 alpha
Revision: 11873
Commit: 4c77384
Build: 2025/02/11
Lazarus: 3.8.0.0
Free Pascal: 3.2.2
Platform: x86_64-Linux-qt5
System: Fedora release 38 (Thirty Eight)
Desktop Environment: KDE
Widgetset library: Qt 5.15.12
This program is free software released under terms of GNU GPL 2
Copyright (C) 2006-2024 Alexander Koblov
   and contributors (see about dialog)
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Executable directory: /tmp/.mount_double798JdS/usr/lib64/doublecmd/
Configuration directory: /home/dandv/.config/doublecmd
Global configuration directory: /tmp/.mount_double798JdS/usr/lib64/doublecmd/settings/
Loading configuration from /home/dandv/.config/doublecmd/
Error loading configuration file /home/dandv/.config/doublecmd/favoritetabs.xml
SystemLocale en_US
SystemLanguage en
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
PollThread: Start polling
PollThread: AddPoll 16
Creating PixmapManager
Loading icon theme Breeze
Loading icon theme Hicolor
Loading icon theme DCTheme
Error loading configuration file /home/dandv/.config/doublecmd/shortcuts.scf
Error loading configuration file /home/dandv/.config/doublecmd/tabs.xml
Creating TFileSystemFileSource
TColumnsFileView.Create components
TColumnsFileView.Create components
FileSystemWatcher thread starting
PollThread: AddPoll 33
UDev: Begin monitoring
Detecting mounts through /proc/self/mounts
PollThread: AddPoll 34
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
frmMain.frmMainShow
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Language directory: /tmp/.mount_double798JdS/usr/lib64/doublecmd/language/
This plugin supports grabbing the mouse only for popup windows
This plugin supports grabbing the mouse only for popup windows
This plugin supports grabbing the mouse only for popup windows
This plugin supports grabbing the mouse only for popup windows
This plugin supports grabbing the mouse only for popup windows
This plugin supports grabbing the mouse only for popup windows
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

![Image](https://github.com/user-attachments/assets/a270c831-fda5-4e5b-9ae8-4645ff14025a)

**Comment by bullestock** [comment]
I still see this problem in doublecmd-qt-latest-x86_64.AppImage (and also in 1.1.23gamma).

**Comment by alexx2000** [comment]
DC loads a font name only at the first start. If you already executed an old DC versions then you should choose a correct font manually.
